### ISSUE TITLE
[Suggestion] Add playerDeathEvent

### ISSUE THREAD

**Issue by TrinitroToluen0** [DiscordBot-PMMP/ChatBridge#21] opened 2024-03-26 02:33 UTC
Add PlayerDeathEvent, so it logs when a player dies and the killer / reason of death

**Comment by n00bslayr94** [comment] 2024-04-08 19:36
Yes! I second this!!

**Comment by JaxkDev** [comment] 2024-07-22 13:09
Duplicate of #15

**Closed as not planned by JaxkDev** 2024-07-22 13:09 UTC
Labels: Type: Duplicate
