### ISSUE TITLE
PM5 Support??

### ISSUE THREAD

**Issue by GabBiswajit** [DiscordBot-PMMP/ChatBridge#11] opened 2023-09-30 14:56 UTC
I think now discord bot also updete to pm5, so can you update this plugin also

**Comment by GabBiswajit** [comment] 2023-09-30 15:37
@JaxkDev  you update the plugin??

**Comment by JaxkDev** [comment] 2023-09-30 15:48
Duplicate of #8

**Closed as not planned by JaxkDev** 2023-09-30 15:48 UTC
Labels: Type: Duplicate
